image:
  hub: intel
  name: trusted-certificate-issuer
  tag: 0.4.0
  pullPolicy: Always

# Any extra arguments for tcs-controller
controllerExtraArgs: {}
#controllerExtraArgs: |-
#  - --csr-full-cert-chain=true
#  - --use-random-nonce=true
