image:
  hub: docker.io
  name: intel/trusted-certificate-issuer
  tag: 0.2.0
  pullPolicy: Always

# Any extra arguments for tcs-controller
controllerExtraArgs: {}
#controllerExtraArgs: |-
#  - --csr-full-cert-chain=true
#  - --use-random-nonce=true
